window.SEARCH_DATA = {
  "meta": {
    "documents_dir": "hils_rag_sample_docs",
    "chunk_size": 800,
    "chunk_overlap": 100,
    "document_count": 10,
    "chunk_count": 13,
    "placeholder_catalog": [
      {
        "key": "ecu_name",
        "placeholder": "{{ECU_NAME}}"
      },
      {
        "key": "bench_name",
        "placeholder": "{{BENCH_NAME}}"
      },
      {
        "key": "sharepoint_site",
        "placeholder": "{{SP_SITE}}"
      }
    ],
    "operator_help": [
      {
        "syntax": "+term",
        "meaning": "必須語"
      },
      {
        "syntax": "-term",
        "meaning": "除外語"
      },
      {
        "syntax": "\"phrase\"",
        "meaning": "フレーズ一致"
      },
      {
        "syntax": "source:value",
        "meaning": "出典ラベル絞り込み"
      },
      {
        "syntax": "title:value",
        "meaning": "タイトル絞り込み"
      }
    ],
    "evaluation_cases": [
      {
        "question": "CAN fault injection の手順を見たい",
        "expected_source_labels": [
          "docx\\can_fault_injection_quick_guide.docx"
        ]
      },
      {
        "question": "DC charging bringup procedure を確認したい",
        "expected_source_labels": [
          "docx\\hils_dc_charging_bringup_procedure.docx"
        ]
      },
      {
        "question": "inverter boot sequence のチェックリストは？",
        "expected_source_labels": [
          "html\\inverter_boot_sequence_checklist.html"
        ]
      },
      {
        "question": "diag session recovery のプレイブックを見たい",
        "expected_source_labels": [
          "md\\ecu_diag_session_recovery_playbook.md"
        ]
      },
      {
        "question": "regenerative brake の test report は？",
        "expected_source_labels": [
          "pptx\\regenerative_brake_hils_test_report.pptx"
        ]
      }
    ]
  },
  "documents": [
    {
      "document_ref": "DOC-001",
      "source_label": "docx\\can_fault_injection_quick_guide.docx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/docx/can_fault_injection_quick_guide.docx",
      "title": "can_fault_injection_quick_guide",
      "file_type": "docx",
      "placeholder_keys": [],
      "chunk_count": 1
    },
    {
      "document_ref": "DOC-002",
      "source_label": "docx\\hils_dc_charging_bringup_procedure.docx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/docx/hils_dc_charging_bringup_procedure.docx",
      "title": "hils_dc_charging_bringup_procedure",
      "file_type": "docx",
      "placeholder_keys": [],
      "chunk_count": 1
    },
    {
      "document_ref": "DOC-003",
      "source_label": "excel\\hils_io_mapping_register.xlsx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/excel/hils_io_mapping_register.xlsx",
      "title": "hils_io_mapping_register",
      "file_type": "xlsx",
      "placeholder_keys": [],
      "chunk_count": 1
    },
    {
      "document_ref": "DOC-004",
      "source_label": "excel\\regression_execution_matrix.xlsx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/excel/regression_execution_matrix.xlsx",
      "title": "regression_execution_matrix",
      "file_type": "xlsx",
      "placeholder_keys": [],
      "chunk_count": 1
    },
    {
      "document_ref": "DOC-005",
      "source_label": "html\\inverter_boot_sequence_checklist.html",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/html/inverter_boot_sequence_checklist.html",
      "title": "inverter_boot_sequence_checklist",
      "file_type": "html",
      "placeholder_keys": [],
      "chunk_count": 2
    },
    {
      "document_ref": "DOC-006",
      "source_label": "html\\thermal_derate_signal_map.html",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/html/thermal_derate_signal_map.html",
      "title": "thermal_derate_signal_map",
      "file_type": "html",
      "placeholder_keys": [],
      "chunk_count": 1
    },
    {
      "document_ref": "DOC-007",
      "source_label": "md\\ecu_diag_session_recovery_playbook.md",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/md/ecu_diag_session_recovery_playbook.md",
      "title": "ecu_diag_session_recovery_playbook",
      "file_type": "md",
      "placeholder_keys": [],
      "chunk_count": 2
    },
    {
      "document_ref": "DOC-008",
      "source_label": "md\\hils_power_mode_transition_notes.md",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/md/hils_power_mode_transition_notes.md",
      "title": "hils_power_mode_transition_notes",
      "file_type": "md",
      "placeholder_keys": [],
      "chunk_count": 2
    },
    {
      "document_ref": "DOC-009",
      "source_label": "pptx\\hils_bench_bringup_review.pptx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/pptx/hils_bench_bringup_review.pptx",
      "title": "hils_bench_bringup_review",
      "file_type": "pptx",
      "placeholder_keys": [],
      "chunk_count": 1
    },
    {
      "document_ref": "DOC-010",
      "source_label": "pptx\\regenerative_brake_hils_test_report.pptx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/pptx/regenerative_brake_hils_test_report.pptx",
      "title": "regenerative_brake_hils_test_report",
      "file_type": "pptx",
      "placeholder_keys": [],
      "chunk_count": 1
    }
  ],
  "chunks": [
    {
      "id": 0,
      "chunk_ref": "DOC-001-C000",
      "document_ref": "DOC-001",
      "source_label": "docx\\can_fault_injection_quick_guide.docx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/docx/can_fault_injection_quick_guide.docx",
      "title": "can_fault_injection_quick_guide",
      "file_type": "docx",
      "chunk_index": 0,
      "text": "CAN Fault Injection Quick Guide\n目的: fault injection の準備、注入条件、観測ポイント、復帰手順を 2 ページ弱の参照用に圧縮する。\n1. Injection families\n2. Decision flow\n3. Notes that often matter\n- trigger condition をログ時刻と同じ粒度で残す。ready後なのか precharge中なのかで意味が変わる。\n- reset 手順を fault 毎に固定しない。bus off clear と full ignition cycle は重みが違う。\n- inject 成功だけで満足しない。fallback path が期待通り単調に進むかを見る。",
      "tokens": [
        "can",
        "fault",
        "injection",
        "quick",
        "guide",
        "目的",
        "目的",
        "fault",
        "injection",
        "準備",
        "準備",
        "注入条件",
        "注入",
        "入条",
        "条件",
        "観測",
        "観測",
        "ポイント",
        "ポイ",
        "イン",
        "ント",
        "復帰手順",
        "復帰",
        "帰手",
        "手順",
        "2",
        "ページ",
        "ペー",
        "ージ",
        "弱",
        "参照用",
        "参照",
        "照用",
        "圧縮",
        "圧縮",
        "する",
        "1",
        "injection",
        "families",
        "2",
        "decision",
        "flow",
        "3",
        "notes",
        "that",
        "often",
        "matter",
        "trigger",
        "condition",
        "ログ",
        "ログ",
        "時刻",
        "時刻",
        "同",
        "粒度",
        "粒度",
        "残",
        "ready",
        "後",
        "なのか",
        "precharge",
        "中",
        "なのかで",
        "意味",
        "意味",
        "変",
        "わる",
        "reset",
        "手順",
        "手順",
        "fault",
        "毎",
        "固定",
        "固定",
        "しない",
        "bus",
        "off",
        "clear",
        "full",
        "ignition",
        "cycle",
        "重",
        "みが",
        "違",
        "inject",
        "成功",
        "成功",
        "だけで",
        "満足",
        "満足",
        "しない",
        "fallback",
        "path",
        "期待通",
        "期待",
        "待通",
        "単調",
        "単調",
        "進",
        "むかを",
        "見"
      ],
      "token_count": 101,
      "placeholder_keys": []
    },
    {
      "id": 1,
      "chunk_ref": "DOC-002-C000",
      "document_ref": "DOC-002",
      "source_label": "docx\\hils_dc_charging_bringup_procedure.docx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/docx/hils_dc_charging_bringup_procedure.docx",
      "title": "hils_dc_charging_bringup_procedure",
      "file_type": "docx",
      "chunk_index": 0,
      "text": "HILS DC Charging Bench Bring-up Procedure\n目的: OBC/DC charging 系の HILS ベンチを朝一で立ち上げるための、前提条件・操作順・確認ログをまとめる。\n1. Scope\n対象は Host PC, dSPACE rack, charger ECU, battery simulator, load emulator。通常運転の量産車条件ではなく、観測優先の bench condition を前提とする。\n2. Preconditions\n3. Bench topology\n4. Startup steps\n1. PSU output on, dSPACE model load, CANoe measurement start.\n2. CHG_ModeReq=Standby を 500 ms 監視し、unexpected wakeup が無いことを確認。\n3. Pilot duty を 5 % -> 10 % -> 50 % に変え、PlugState=Connected を確認。\n4. Precharge complete 後に ChargeEnable=1 を送り、HV current feedback を確認。\n5. Useful log fragment\n[07:52:14.201] PilotDuty=10%\n[07:52:14.540] PlugState=Connected\n[07:52:16.028] ChargeEnable=1, HVCurrent=8.2A",
      "tokens": [
        "hils",
        "dc",
        "charging",
        "bench",
        "bring",
        "up",
        "procedure",
        "目的",
        "目的",
        "obc",
        "dc",
        "charging",
        "系",
        "hils",
        "ベンチ",
        "ベン",
        "ンチ",
        "朝一",
        "朝一",
        "立",
        "上",
        "げるための",
        "前提条件",
        "前提",
        "提条",
        "条件",
        "操作順",
        "操作",
        "作順",
        "確認",
        "確認",
        "ログ",
        "ログ",
        "をまとめる",
        "1",
        "scope",
        "対象",
        "対象",
        "host",
        "pc",
        "dspace",
        "rack",
        "charger",
        "ecu",
        "battery",
        "simulator",
        "load",
        "emulator",
        "通常運転",
        "通常",
        "常運",
        "運転",
        "量産車条件",
        "量産",
        "産車",
        "車条",
        "条件",
        "ではなく",
        "観測優先",
        "観測",
        "測優",
        "優先",
        "bench",
        "condition",
        "前提",
        "前提",
        "とする",
        "2",
        "preconditions",
        "3",
        "bench",
        "topology",
        "4",
        "startup",
        "steps",
        "1",
        "psu",
        "output",
        "on",
        "dspace",
        "model",
        "load",
        "canoe",
        "measurement",
        "start",
        "2",
        "chg_modereq",
        "standby",
        "500",
        "ms",
        "監視",
        "監視",
        "unexpected",
        "wakeup",
        "無",
        "いことを",
        "確認",
        "確認",
        "3",
        "pilot",
        "duty",
        "5",
        "10",
        "50",
        "変",
        "plugstate",
        "connected",
        "確認",
        "確認",
        "4",
        "precharge",
        "complete",
        "後",
        "chargeenable",
        "1",
        "送",
        "hv",
        "current",
        "feedback",
        "確認",
        "確認",
        "5",
        "useful",
        "log",
        "fragment",
        "07",
        "52",
        "14",
        "201",
        "pilotduty",
        "10",
        "07",
        "52",
        "14",
        "540",
        "plugstate",
        "connected",
        "07",
        "52",
        "16",
        "028",
        "chargeenable",
        "1",
        "hvcurrent",
        "8",
        "2a"
      ],
      "token_count": 146,
      "placeholder_keys": []
    },
    {
      "id": 2,
      "chunk_ref": "DOC-003-C000",
      "document_ref": "DOC-003",
      "source_label": "excel\\hils_io_mapping_register.xlsx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/excel/hils_io_mapping_register.xlsx",
      "title": "hils_io_mapping_register",
      "file_type": "xlsx",
      "chunk_index": 0,
      "text": "[Sheet] SignalMap\nDomain | Signal | Direction | Rate ms | Source | Sink | Status | Comment\nPower | KL15 | In | 10 | VCU stub | INV_MAIN | Mapped | boot trigger\nPower | HVBus | Out | 10 | Battery sim | VCU logic | Review | scale check\nBrake | RegenReq | In | 20 | Brake model | VCU logic | Mapped\nDiag | TesterPresent | In | 100 | CANoe | Gateway | Missing | DBC alias pending\nThermal | CoolantTemp | In | 20 | Plant | INV_MAIN | Review | sensor filtering\nMotor | TorqueFeedback | Out | 10 | INV_MAIN | Logger | Mapped\n[Sheet] Summary\nHILS IO Mapping Register\nStatus | Count\nMapped | 3\nReview | 2\nMissing | 1",
      "tokens": [
        "sheet",
        "signalmap",
        "domain",
        "signal",
        "direction",
        "rate",
        "ms",
        "source",
        "sink",
        "status",
        "comment",
        "power",
        "kl15",
        "in",
        "10",
        "vcu",
        "stub",
        "inv_main",
        "mapped",
        "boot",
        "trigger",
        "power",
        "hvbus",
        "out",
        "10",
        "battery",
        "sim",
        "vcu",
        "logic",
        "review",
        "scale",
        "check",
        "brake",
        "regenreq",
        "in",
        "20",
        "brake",
        "model",
        "vcu",
        "logic",
        "mapped",
        "diag",
        "testerpresent",
        "in",
        "100",
        "canoe",
        "gateway",
        "missing",
        "dbc",
        "alias",
        "pending",
        "thermal",
        "coolanttemp",
        "in",
        "20",
        "plant",
        "inv_main",
        "review",
        "sensor",
        "filtering",
        "motor",
        "torquefeedback",
        "out",
        "10",
        "inv_main",
        "logger",
        "mapped",
        "sheet",
        "summary",
        "hils",
        "io",
        "mapping",
        "register",
        "status",
        "count",
        "mapped",
        "3",
        "review",
        "2",
        "missing",
        "1"
      ],
      "token_count": 81,
      "placeholder_keys": []
    },
    {
      "id": 3,
      "chunk_ref": "DOC-004-C000",
      "document_ref": "DOC-004",
      "source_label": "excel\\regression_execution_matrix.xlsx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/excel/regression_execution_matrix.xlsx",
      "title": "regression_execution_matrix",
      "file_type": "xlsx",
      "chunk_index": 0,
      "text": "[Sheet] Coverage\nRegression Execution Matrix\nResult | Count\nPass | 2\nFail | 1\nWatch | 1\nBlocked | 1\n[Sheet] Execution\nTestID | Feature | Bench | Owner | Priority | Result | Notes\nTC-101 | power mode | Bench-A | Kimura | High | Pass | baseline ready\nTC-107 | regen brake | Bench-B | Arai | High | Fail | RB-07 repeat\nTC-112 | diag recovery | Bench-A | Sato | Med | Watch | session linger\nTC-130 | thermal derate | Bench-C | Ito | Med | Pass | level2 reached\nTC-145 | dc charge | Bench-B | Nakamura | Low | Blocked | pilot stub issue",
      "tokens": [
        "sheet",
        "coverage",
        "regression",
        "execution",
        "matrix",
        "result",
        "count",
        "pass",
        "2",
        "fail",
        "1",
        "watch",
        "1",
        "blocked",
        "1",
        "sheet",
        "execution",
        "testid",
        "feature",
        "bench",
        "owner",
        "priority",
        "result",
        "notes",
        "tc",
        "101",
        "power",
        "mode",
        "bench",
        "a",
        "kimura",
        "high",
        "pass",
        "baseline",
        "ready",
        "tc",
        "107",
        "regen",
        "brake",
        "bench",
        "b",
        "arai",
        "high",
        "fail",
        "rb",
        "07",
        "repeat",
        "tc",
        "112",
        "diag",
        "recovery",
        "bench",
        "a",
        "sato",
        "med",
        "watch",
        "session",
        "linger",
        "tc",
        "130",
        "thermal",
        "derate",
        "bench",
        "c",
        "ito",
        "med",
        "pass",
        "level2",
        "reached",
        "tc",
        "145",
        "dc",
        "charge",
        "bench",
        "b",
        "nakamura",
        "low",
        "blocked",
        "pilot",
        "stub",
        "issue"
      ],
      "token_count": 81,
      "placeholder_keys": []
    },
    {
      "id": 4,
      "chunk_ref": "DOC-005-C000",
      "document_ref": "DOC-005",
      "source_label": "html\\inverter_boot_sequence_checklist.html",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/html/inverter_boot_sequence_checklist.html",
      "title": "inverter_boot_sequence_checklist",
      "file_type": "html",
      "chunk_index": 0,
      "text": "HILS Inverter Boot Sequence Checklist\nHILS Inverter Boot Sequence Checklist\n目的: インバータ ECU の起動手順を、前提条件・分岐条件・ログ確認点ごとに分割しやすい形で残す。\nSections\n1. Scope\n2. Preconditions\n3. Boot Steps\n4. Verification\n5. Rollback\n1. Scope\n対象ベンチは dSPACE SCALEXIO + バッテリシミュレータ + インバータプラント。対象 ECU は INV_MAIN、CANoe から起動コマンドを発行する。\n2. Preconditions\n項目\n期待値\n備考\n12V supply\n13.2 +/- 0.2 V\n低いと precharge 前に brownout が出る\nHV simulated bus\n360 V standby\n起動後 340 V を下回らないこと\nCAN gateway\nNode state = operational\n起動直後 500 ms 以内に heartbeat を受信\n3. Boot Steps\nベンチ電源投入。PSU と HIL ラックが Ready を返すまで待機。\nCANoe configuration をロードし、VCU_IGN_CMD=1 を 100 ms 周期で送信。\nINV_MAIN.State が\nPRECHARGE\nに遷移することを確認。\nHV bus > 340 V を満たしたら TorqueEnableReq=1 を送る。\nState=READY かつ DTC count=0 なら起動完了。\n注: 手順 3 で 2 秒以上滞留した場合、FaultLatch より先に SupplyDip を疑う。\n4. Verification Cues",
      "tokens": [
        "hils",
        "inverter",
        "boot",
        "sequence",
        "checklist",
        "hils",
        "inverter",
        "boot",
        "sequence",
        "checklist",
        "目的",
        "目的",
        "インバータ",
        "イン",
        "ンバ",
        "バー",
        "ータ",
        "ecu",
        "起動手順",
        "起動",
        "動手",
        "手順",
        "前提条件",
        "前提",
        "提条",
        "条件",
        "分岐条件",
        "分岐",
        "岐条",
        "条件",
        "ログ",
        "ログ",
        "確認点",
        "確認",
        "認点",
        "ごとに",
        "分割",
        "分割",
        "しやすい",
        "形",
        "残",
        "sections",
        "1",
        "scope",
        "2",
        "preconditions",
        "3",
        "boot",
        "steps",
        "4",
        "verification",
        "5",
        "rollback",
        "1",
        "scope",
        "対象",
        "対象",
        "ベンチ",
        "ベン",
        "ンチ",
        "dspace",
        "scalexio",
        "バッテリシミュレータ",
        "バッ",
        "ッテ",
        "テリ",
        "リシ",
        "シミ",
        "ミュ",
        "ュレ",
        "レー",
        "ータ",
        "インバータプラント",
        "イン",
        "ンバ",
        "バー",
        "ータ",
        "タプ",
        "プラ",
        "ラン",
        "ント",
        "対象",
        "対象",
        "ecu",
        "inv_main",
        "canoe",
        "から",
        "起動",
        "起動",
        "コマンド",
        "コマ",
        "マン",
        "ンド",
        "発行",
        "発行",
        "する",
        "2",
        "preconditions",
        "項目",
        "項目",
        "期待値",
        "期待",
        "待値",
        "備考",
        "備考",
        "12v",
        "supply",
        "13",
        "2",
        "0",
        "2",
        "v",
        "低",
        "いと",
        "precharge",
        "前",
        "brownout",
        "出",
        "hv",
        "simulated",
        "bus",
        "360",
        "v",
        "standby",
        "起動後",
        "起動",
        "動後",
        "340",
        "v",
        "下回",
        "下回",
        "らないこと",
        "can",
        "gateway",
        "node",
        "state",
        "operational",
        "起動直後",
        "起動",
        "動直",
        "直後",
        "500",
        "ms",
        "以内",
        "以内",
        "heartbeat",
        "受信",
        "受信",
        "3",
        "boot",
        "steps",
        "ベンチ",
        "ベン",
        "ンチ",
        "電源投入",
        "電源",
        "源投",
        "投入",
        "psu",
        "hil",
        "ラック",
        "ラッ",
        "ック",
        "ready",
        "返",
        "すまで",
        "待機",
        "待機",
        "canoe",
        "configuration",
        "ロード",
        "ロー",
        "ード",
        "vcu_ign_cmd",
        "1",
        "100",
        "ms",
        "周期",
        "周期",
        "送信",
        "送信",
        "inv_main",
        "state",
        "precharge",
        "遷移",
        "遷移",
        "することを",
        "確認",
        "確認",
        "hv",
        "bus",
        "340",
        "v",
        "満",
        "たしたら",
        "torqueenablereq",
        "1",
        "送",
        "state",
        "ready",
        "かつ",
        "dtc",
        "count",
        "0",
        "なら",
        "起動完了",
        "起動",
        "動完",
        "完了",
        "注",
        "手順",
        "手順",
        "3",
        "2",
        "秒以上滞留",
        "秒以",
        "以上",
        "上滞",
        "滞留",
        "した",
        "場合",
        "場合",
        "faultlatch",
        "先",
        "supplydip",
        "疑",
        "4",
        "verification",
        "cues"
      ],
      "token_count": 229,
      "placeholder_keys": []
    },
    {
      "id": 5,
      "chunk_ref": "DOC-005-C001",
      "document_ref": "DOC-005",
      "source_label": "html\\inverter_boot_sequence_checklist.html",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/html/inverter_boot_sequence_checklist.html",
      "title": "inverter_boot_sequence_checklist",
      "file_type": "html",
      "chunk_index": 1,
      "text": "ADY かつ DTC count=0 なら起動完了。\n注: 手順 3 で 2 秒以上滞留した場合、FaultLatch より先に SupplyDip を疑う。\n4. Verification Cues\n[08:14:22.105] IGN_CMD=1\n[08:14:22.442] INV_MAIN.State=PRECHARGE\n[08:14:23.018] HVBus=347.6V\n[08:14:23.121] INV_MAIN.State=READY\nREADY 遷移後 500 ms 以内に torque response dummy signal が 0 Nm を維持していること。振れがあるなら model side initial condition mismatch を切り分ける。\n5. Rollback Path\n異常時は TorqueEnableReq=0 → IGN_CMD=0 → PSU output off の順で戻す。ログ採取が未完なら bench reset を先に打たない。",
      "tokens": [
        "ady",
        "かつ",
        "dtc",
        "count",
        "0",
        "なら",
        "起動完了",
        "起動",
        "動完",
        "完了",
        "注",
        "手順",
        "手順",
        "3",
        "2",
        "秒以上滞留",
        "秒以",
        "以上",
        "上滞",
        "滞留",
        "した",
        "場合",
        "場合",
        "faultlatch",
        "先",
        "supplydip",
        "疑",
        "4",
        "verification",
        "cues",
        "08",
        "14",
        "22",
        "105",
        "ign_cmd",
        "1",
        "08",
        "14",
        "22",
        "442",
        "inv_main",
        "state",
        "precharge",
        "08",
        "14",
        "23",
        "018",
        "hvbus",
        "347",
        "6v",
        "08",
        "14",
        "23",
        "121",
        "inv_main",
        "state",
        "ready",
        "ready",
        "遷移後",
        "遷移",
        "移後",
        "500",
        "ms",
        "以内",
        "以内",
        "torque",
        "response",
        "dummy",
        "signal",
        "0",
        "nm",
        "維持",
        "維持",
        "していること",
        "振",
        "れがあるなら",
        "model",
        "side",
        "initial",
        "condition",
        "mismatch",
        "切",
        "分",
        "ける",
        "5",
        "rollback",
        "path",
        "異常時",
        "異常",
        "常時",
        "torqueenablereq",
        "0",
        "ign_cmd",
        "0",
        "psu",
        "output",
        "off",
        "順",
        "戻",
        "ログ",
        "ログ",
        "採取",
        "採取",
        "未完",
        "未完",
        "なら",
        "bench",
        "reset",
        "先",
        "打",
        "たない"
      ],
      "token_count": 111,
      "placeholder_keys": []
    },
    {
      "id": 6,
      "chunk_ref": "DOC-006-C000",
      "document_ref": "DOC-006",
      "source_label": "html\\thermal_derate_signal_map.html",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/html/thermal_derate_signal_map.html",
      "title": "thermal_derate_signal_map",
      "file_type": "html",
      "chunk_index": 0,
      "text": "Thermal Derate Signal Map\nIntent:\n熱デレート判定に使う信号群を、由来・更新周期・判定閾値・ありがちな誤解まで含めてまとめる。\nThermal Derate Signal Map\nSignal Matrix\nSignal\nSource\nRate\nTrip / Release\nNotes\nMCU_StatorTempFilt\nPlant thermal model\n10 ms\n160 / 150 degC\n一次遅れ後の値。raw temp と混同しやすい。\nINV_CoolantTemp\nSensor stub\n20 ms\n65 / 60 degC\n通信欠落時は last-good-hold。\nDerateRequestLevel\nControl SW\n10 ms\n0-3 state\nレベル3で torque hard cap。\nExpected Narrative\n通常は MCU_StatorTempFilt が先に立ち上がり、その後 INV_CoolantTemp が追従する。両者が同時に跳ねる場合、plant 初期条件かセンサスケーリングの疑いが強い。\nCase A:\n- stator temp crosses 160 degC for 280 ms\n- derate level rises 0 -> 1 -> 2\n- torque limit ramps 280 -> 220 -> 180 Nm\nFlow View\nReview Questions\n閾値は raw 値か filtered 値か。\n解除条件に hysteresis があるか。\nDerateRequestLevel と torque cap の関係は単調か。",
      "tokens": [
        "thermal",
        "derate",
        "signal",
        "map",
        "intent",
        "熱",
        "デレート",
        "デレ",
        "レー",
        "ート",
        "判定",
        "判定",
        "使",
        "信号群",
        "信号",
        "号群",
        "由来",
        "由来",
        "更新周期",
        "更新",
        "新周",
        "周期",
        "判定閾値",
        "判定",
        "定閾",
        "閾値",
        "ありがちな",
        "誤解",
        "誤解",
        "含",
        "めてまとめる",
        "thermal",
        "derate",
        "signal",
        "map",
        "signal",
        "matrix",
        "signal",
        "source",
        "rate",
        "trip",
        "release",
        "notes",
        "mcu_statortempfilt",
        "plant",
        "thermal",
        "model",
        "10",
        "ms",
        "160",
        "150",
        "degc",
        "一次遅",
        "一次",
        "次遅",
        "後",
        "値",
        "raw",
        "temp",
        "混同",
        "混同",
        "しやすい",
        "inv_coolanttemp",
        "sensor",
        "stub",
        "20",
        "ms",
        "65",
        "60",
        "degc",
        "通信欠落時",
        "通信",
        "信欠",
        "欠落",
        "落時",
        "last",
        "good",
        "hold",
        "deraterequestlevel",
        "control",
        "sw",
        "10",
        "ms",
        "0",
        "3",
        "state",
        "レベル",
        "レベ",
        "ベル",
        "3",
        "torque",
        "hard",
        "cap",
        "expected",
        "narrative",
        "通常",
        "通常",
        "mcu_statortempfilt",
        "先",
        "立",
        "上",
        "がり",
        "その",
        "後",
        "inv_coolanttemp",
        "追従",
        "追従",
        "する",
        "両者",
        "両者",
        "同時",
        "同時",
        "跳",
        "ねる",
        "場合",
        "場合",
        "plant",
        "初期条件",
        "初期",
        "期条",
        "条件",
        "センサスケーリング",
        "セン",
        "ンサ",
        "サス",
        "スケ",
        "ケー",
        "ーリ",
        "リン",
        "ング",
        "疑",
        "いが",
        "強",
        "case",
        "a",
        "stator",
        "temp",
        "crosses",
        "160",
        "degc",
        "for",
        "280",
        "ms",
        "derate",
        "level",
        "rises",
        "0",
        "1",
        "2",
        "torque",
        "limit",
        "ramps",
        "280",
        "220",
        "180",
        "nm",
        "flow",
        "view",
        "review",
        "questions",
        "閾値",
        "閾値",
        "raw",
        "値",
        "filtered",
        "値",
        "解除条件",
        "解除",
        "除条",
        "条件",
        "hysteresis",
        "があるか",
        "deraterequestlevel",
        "torque",
        "cap",
        "関係",
        "関係",
        "単調",
        "単調"
      ],
      "token_count": 179,
      "placeholder_keys": []
    },
    {
      "id": 7,
      "chunk_ref": "DOC-007-C000",
      "document_ref": "DOC-007",
      "source_label": "md\\ecu_diag_session_recovery_playbook.md",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/md/ecu_diag_session_recovery_playbook.md",
      "title": "ecu_diag_session_recovery_playbook",
      "file_type": "md",
      "chunk_index": 0,
      "text": "# ECU Diag Session Recovery Playbook\n## Purpose\nCAN 診断セッション遷移を誤って残したまま通常試験に戻した時の、復旧手順を短くまとめる。\n## Trigger Conditions\n- Extended session のまま ignition cycle を模擬した\n- Security access unlock 後に tester が切断された\n- `0x7F 0x78` が連続し、通常通信周期が乱れた\n## Recovery Pattern\n### Pattern A: Soft unwind\n1. Tester present を 2 周期維持する\n2. `0x10 0x01` で default session を要求\n3. 応答確認後、5 秒待って cyclic traffic を再開\n### Pattern B: Forced bench reset\n前提:\n- soft unwind が失敗\n- DTC snapshot 採取済み\n- 12V recycle による副作用を受容できる\n```text\nReset order:\n1) Torque inhibit\n2) Session log export\n3) IGN off\n4) 12V drop 3 s\n5) IGN on\n```\n## Non-obvious Assumptions\n- default session へ戻っても application side latch が即解除されるとは限らない\n- BMS_SIM 側が stale heartbeat を維持していると、復旧したように見えて再現性が崩れる\n## Appendix: service IDs seen in the field\n| SID | Meaning | Common mis",
      "tokens": [
        "ecu",
        "diag",
        "session",
        "recovery",
        "playbook",
        "purpose",
        "can",
        "診断",
        "診断",
        "セッション",
        "セッ",
        "ッシ",
        "ショ",
        "ョン",
        "遷移",
        "遷移",
        "誤",
        "って",
        "残",
        "したまま",
        "通常試験",
        "通常",
        "常試",
        "試験",
        "戻",
        "した",
        "時",
        "復旧手順",
        "復旧",
        "旧手",
        "手順",
        "短",
        "くまとめる",
        "trigger",
        "conditions",
        "extended",
        "session",
        "のまま",
        "ignition",
        "cycle",
        "模擬",
        "模擬",
        "した",
        "security",
        "access",
        "unlock",
        "後",
        "tester",
        "切断",
        "切断",
        "された",
        "0x7f",
        "0x78",
        "連続",
        "連続",
        "通常通信周期",
        "通常",
        "常通",
        "通信",
        "信周",
        "周期",
        "乱",
        "れた",
        "recovery",
        "pattern",
        "pattern",
        "a",
        "soft",
        "unwind",
        "1",
        "tester",
        "present",
        "2",
        "周期維持",
        "周期",
        "期維",
        "維持",
        "する",
        "2",
        "0x10",
        "0x01",
        "default",
        "session",
        "要求",
        "要求",
        "3",
        "応答確認後",
        "応答",
        "答確",
        "確認",
        "認後",
        "5",
        "秒待",
        "秒待",
        "って",
        "cyclic",
        "traffic",
        "再開",
        "再開",
        "pattern",
        "b",
        "forced",
        "bench",
        "reset",
        "前提",
        "前提",
        "soft",
        "unwind",
        "失敗",
        "失敗",
        "dtc",
        "snapshot",
        "採取済",
        "採取",
        "取済",
        "12v",
        "recycle",
        "による",
        "副作用",
        "副作",
        "作用",
        "受容",
        "受容",
        "できる",
        "text",
        "reset",
        "order",
        "1",
        "torque",
        "inhibit",
        "2",
        "session",
        "log",
        "export",
        "3",
        "ign",
        "off",
        "4",
        "12v",
        "drop",
        "3",
        "s",
        "5",
        "ign",
        "on",
        "non",
        "obvious",
        "assumptions",
        "default",
        "session",
        "戻",
        "っても",
        "application",
        "side",
        "latch",
        "即解除",
        "即解",
        "解除",
        "されるとは",
        "限",
        "らない",
        "bms_sim",
        "側",
        "stale",
        "heartbeat",
        "維持",
        "維持",
        "していると",
        "復旧",
        "復旧",
        "したように",
        "見",
        "えて",
        "再現性",
        "再現",
        "現性",
        "崩",
        "れる",
        "appendix",
        "service",
        "ids",
        "seen",
        "in",
        "the",
        "field",
        "sid",
        "meaning",
        "common",
        "mis"
      ],
      "token_count": 189,
      "placeholder_keys": []
    },
    {
      "id": 8,
      "chunk_ref": "DOC-007-C001",
      "document_ref": "DOC-007",
      "source_label": "md\\ecu_diag_session_recovery_playbook.md",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/md/ecu_diag_session_recovery_playbook.md",
      "title": "ecu_diag_session_recovery_playbook",
      "file_type": "md",
      "chunk_index": 1,
      "text": "t を維持していると、復旧したように見えて再現性が崩れる\n## Appendix: service IDs seen in the field\n| SID | Meaning | Common misuse |\n| --- | --- | --- |\n| `0x10` | Diagnostic session control | response positive だけ見て内部状態を見ない |\n| `0x27` | Security access | seed/key 成功後のタイムアウト管理を忘れる |\n| `0x28` | Communication control | mute 範囲を広げすぎて bench 側も見失う |",
      "tokens": [
        "t",
        "維持",
        "維持",
        "していると",
        "復旧",
        "復旧",
        "したように",
        "見",
        "えて",
        "再現性",
        "再現",
        "現性",
        "崩",
        "れる",
        "appendix",
        "service",
        "ids",
        "seen",
        "in",
        "the",
        "field",
        "sid",
        "meaning",
        "common",
        "misuse",
        "0x10",
        "diagnostic",
        "session",
        "control",
        "response",
        "positive",
        "見",
        "内部状態",
        "内部",
        "部状",
        "状態",
        "見",
        "ない",
        "0x27",
        "security",
        "access",
        "seed",
        "key",
        "成功後",
        "成功",
        "功後",
        "タイムアウト",
        "タイ",
        "イム",
        "ムア",
        "アウ",
        "ウト",
        "管理",
        "管理",
        "忘",
        "れる",
        "0x28",
        "communication",
        "control",
        "mute",
        "範囲",
        "範囲",
        "広",
        "げすぎて",
        "bench",
        "側",
        "見失",
        "見失"
      ],
      "token_count": 68,
      "placeholder_keys": []
    },
    {
      "id": 9,
      "chunk_ref": "DOC-008-C000",
      "document_ref": "DOC-008",
      "source_label": "md\\hils_power_mode_transition_notes.md",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/md/hils_power_mode_transition_notes.md",
      "title": "hils_power_mode_transition_notes",
      "file_type": "md",
      "chunk_index": 0,
      "text": "# HILS Power Mode Transition Notes\n## Context\n- 対象 ECU: VCU_A / INV_MAIN / BMS_SIM\n- 観測目的: KL15 から READY までの遷移と、その途中の `PRECHARGE` 滞留条件\n- 想定利用: 手順書RAGでのチャンク検索、異常系説明、ログ根拠の抽出\n## Timeline Snapshot\n![power mode timeline](../assets/power_mode_timeline.svg)\n1. `KL15=ON`\n2. `VCU.PowerMode = BOOT`\n3. `HV_PrechargeRelay = ON`\n4. `HVBus >= 340V`\n5. `INV_MAIN.State = READY`\n## What Usually Goes Wrong\n### Case 1: PRECHARGE stall\n- 症状: `INV_MAIN.State=PRECHARGE` のまま 2.0 s を超える\n- まず疑うもの:\n- PSU current limit\n- battery model initial SOC mismatch\n- relay feedback inversion\n```text\n[09:02:11.004] KL15 ON\n[09:02:11.292] Precharge relay ON\n[09:02:13.401] HVBus = 301.8V\n[09:02:13.408] timeout -> PRECHARGE_STALL\n```\n### Case 2: READY entered, torque still blocked\n- 状況としては READY でも、別系統で `TorquePathInhibit=1` が残る",
      "tokens": [
        "hils",
        "power",
        "mode",
        "transition",
        "notes",
        "context",
        "対象",
        "対象",
        "ecu",
        "vcu_a",
        "inv_main",
        "bms_sim",
        "観測目的",
        "観測",
        "測目",
        "目的",
        "kl15",
        "から",
        "ready",
        "までの",
        "遷移",
        "遷移",
        "その",
        "途中",
        "途中",
        "precharge",
        "滞留条件",
        "滞留",
        "留条",
        "条件",
        "想定利用",
        "想定",
        "定利",
        "利用",
        "手順書",
        "手順",
        "順書",
        "rag",
        "での",
        "チャンク",
        "チャ",
        "ャン",
        "ンク",
        "検索",
        "検索",
        "異常系説明",
        "異常",
        "常系",
        "系説",
        "説明",
        "ログ",
        "ログ",
        "根拠",
        "根拠",
        "抽出",
        "抽出",
        "timeline",
        "snapshot",
        "power",
        "mode",
        "timeline",
        "assets",
        "power_mode_timeline",
        "svg",
        "1",
        "kl15",
        "on",
        "2",
        "vcu",
        "powermode",
        "boot",
        "3",
        "hv_prechargerelay",
        "on",
        "4",
        "hvbus",
        "340v",
        "5",
        "inv_main",
        "state",
        "ready",
        "what",
        "usually",
        "goes",
        "wrong",
        "case",
        "1",
        "precharge",
        "stall",
        "症状",
        "症状",
        "inv_main",
        "state",
        "precharge",
        "のまま",
        "2",
        "0",
        "s",
        "超",
        "える",
        "まず",
        "疑",
        "うもの",
        "psu",
        "current",
        "limit",
        "battery",
        "model",
        "initial",
        "soc",
        "mismatch",
        "relay",
        "feedback",
        "inversion",
        "text",
        "09",
        "02",
        "11",
        "004",
        "kl15",
        "on",
        "09",
        "02",
        "11",
        "292",
        "precharge",
        "relay",
        "on",
        "09",
        "02",
        "13",
        "401",
        "hvbus",
        "301",
        "8v",
        "09",
        "02",
        "13",
        "408",
        "timeout",
        "precharge_stall",
        "case",
        "2",
        "ready",
        "entered",
        "torque",
        "still",
        "blocked",
        "状況",
        "状況",
        "としては",
        "ready",
        "でも",
        "別系統",
        "別系",
        "系統",
        "torquepathinhibit",
        "1",
        "残"
      ],
      "token_count": 159,
      "placeholder_keys": []
    },
    {
      "id": 10,
      "chunk_ref": "DOC-008-C001",
      "document_ref": "DOC-008",
      "source_label": "md\\hils_power_mode_transition_notes.md",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/md/hils_power_mode_transition_notes.md",
      "title": "hils_power_mode_transition_notes",
      "file_type": "md",
      "chunk_index": 1,
      "text": "``\n### Case 2: READY entered, torque still blocked\n- 状況としては READY でも、別系統で `TorquePathInhibit=1` が残る\n- この場合は power mode の問題ではなく、driveline interlock か diag session 残留の可能性が高い\n## Review Chunk Candidates\n| Chunk candidate | Why it is useful |\n| --- | --- |\n| Preconditions block | 起動前条件だけを検索したいケースがある |\n| Timeline steps | 状態遷移の系列知識として切り出しやすい |\n| Failure snippets | ログ由来の問いに強い |\n| Recovery hints | 単なる事象説明と対策を分離できる |",
      "tokens": [
        "case",
        "2",
        "ready",
        "entered",
        "torque",
        "still",
        "blocked",
        "状況",
        "状況",
        "としては",
        "ready",
        "でも",
        "別系統",
        "別系",
        "系統",
        "torquepathinhibit",
        "1",
        "残",
        "この",
        "場合",
        "場合",
        "power",
        "mode",
        "問題",
        "問題",
        "ではなく",
        "driveline",
        "interlock",
        "diag",
        "session",
        "残留",
        "残留",
        "可能性",
        "可能",
        "能性",
        "高",
        "review",
        "chunk",
        "candidates",
        "chunk",
        "candidate",
        "why",
        "it",
        "is",
        "useful",
        "preconditions",
        "block",
        "起動前条件",
        "起動",
        "動前",
        "前条",
        "条件",
        "だけを",
        "検索",
        "検索",
        "したい",
        "ケース",
        "ケー",
        "ース",
        "がある",
        "timeline",
        "steps",
        "状態遷移",
        "状態",
        "態遷",
        "遷移",
        "系列知識",
        "系列",
        "列知",
        "知識",
        "切",
        "出",
        "しやすい",
        "failure",
        "snippets",
        "ログ",
        "ログ",
        "由来",
        "由来",
        "問",
        "いに",
        "強",
        "recovery",
        "hints",
        "単",
        "なる",
        "事象説明",
        "事象",
        "象説",
        "説明",
        "対策",
        "対策",
        "分離",
        "分離",
        "できる"
      ],
      "token_count": 95,
      "placeholder_keys": []
    },
    {
      "id": 11,
      "chunk_ref": "DOC-009-C000",
      "document_ref": "DOC-009",
      "source_label": "pptx\\hils_bench_bringup_review.pptx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/pptx/hils_bench_bringup_review.pptx",
      "title": "hils_bench_bringup_review",
      "file_type": "pptx",
      "chunk_index": 0,
      "text": "HILS Bench Bring-up Review\nsample deck for chunking / architecture / checklist / issue summary\nBench Topology\nHost PC\ndSPACE HIL\nVCU ECU\nBattery Sim\nポイント\n: ECU, plant, automation\nの境界が明示される資料は、\nRAG\nで\n'\nどこに責務があるか\n'\nを拾いやすい。\nMorning Bring-up Checklist\n1. PSU / rack / simulator power on\n2. model load and CANoe start\n3. IGN command and precharge monitor\n4. READY confirmation and torque inhibit check\n5. archive logs before next scenario\nOpen Issues\nID\nSymptom\nLikely layer\nStatus\nB-04\nPRECHARGE stall\nplant init\nopen\nB-08\ndiag timeout\ngateway\nwatch\nB-11\ntorque inhibit stuck\nVCU logic\ninvestigate",
      "tokens": [
        "hils",
        "bench",
        "bring",
        "up",
        "review",
        "sample",
        "deck",
        "for",
        "chunking",
        "architecture",
        "checklist",
        "issue",
        "summary",
        "bench",
        "topology",
        "host",
        "pc",
        "dspace",
        "hil",
        "vcu",
        "ecu",
        "battery",
        "sim",
        "ポイント",
        "ポイ",
        "イン",
        "ント",
        "ecu",
        "plant",
        "automation",
        "境界",
        "境界",
        "明示",
        "明示",
        "される",
        "資料",
        "資料",
        "rag",
        "どこに",
        "責務",
        "責務",
        "があるか",
        "拾",
        "いやすい",
        "morning",
        "bring",
        "up",
        "checklist",
        "1",
        "psu",
        "rack",
        "simulator",
        "power",
        "on",
        "2",
        "model",
        "load",
        "and",
        "canoe",
        "start",
        "3",
        "ign",
        "command",
        "and",
        "precharge",
        "monitor",
        "4",
        "ready",
        "confirmation",
        "and",
        "torque",
        "inhibit",
        "check",
        "5",
        "archive",
        "logs",
        "before",
        "next",
        "scenario",
        "open",
        "issues",
        "id",
        "symptom",
        "likely",
        "layer",
        "status",
        "b",
        "04",
        "precharge",
        "stall",
        "plant",
        "init",
        "open",
        "b",
        "08",
        "diag",
        "timeout",
        "gateway",
        "watch",
        "b",
        "11",
        "torque",
        "inhibit",
        "stuck",
        "vcu",
        "logic",
        "investigate"
      ],
      "token_count": 107,
      "placeholder_keys": []
    },
    {
      "id": 12,
      "chunk_ref": "DOC-010-C000",
      "document_ref": "DOC-010",
      "source_label": "pptx\\regenerative_brake_hils_test_report.pptx",
      "source_url": "file:///C:/Users/Kaoru/Documents/RAG_Engine/hils_rag_sample_docs/pptx/regenerative_brake_hils_test_report.pptx",
      "title": "regenerative_brake_hils_test_report",
      "file_type": "pptx",
      "chunk_index": 0,
      "text": "Regenerative Brake HILS Test Report\nsample report deck / mixed evidence types / action-oriented notes\nResult Summary\nScenario\nVehicle speed\nSOC\nExpected\nObserved\nRB-01\n40 km/h\n55%\nregen available\npass\nRB-02\n80 km/h\n95%\nregen reduced\npass\nRB-03\n20 km/h\n30%\nblended brake\nmonitor\nRB-07\n60 km/h\n15%\ntorque cap release\nfail\nSignal Story\n回生トルク立上りと\nwheel decel\nが一致しない場合、制御失敗ではなく\nplant brake drag\nを疑う。\nNext Actions\nA. RB-07\nの\nSOC\n低条件を再実行\nB. battery internal resistance map\nを固定して比較\nC. hydraulic brake model drag term\nを分離計測\nD. report template\nに\ntrigger / evidence / rollback\nを追加",
      "tokens": [
        "regenerative",
        "brake",
        "hils",
        "test",
        "report",
        "sample",
        "report",
        "deck",
        "mixed",
        "evidence",
        "types",
        "action",
        "oriented",
        "notes",
        "result",
        "summary",
        "scenario",
        "vehicle",
        "speed",
        "soc",
        "expected",
        "observed",
        "rb",
        "01",
        "40",
        "km",
        "h",
        "55",
        "regen",
        "available",
        "pass",
        "rb",
        "02",
        "80",
        "km",
        "h",
        "95",
        "regen",
        "reduced",
        "pass",
        "rb",
        "03",
        "20",
        "km",
        "h",
        "30",
        "blended",
        "brake",
        "monitor",
        "rb",
        "07",
        "60",
        "km",
        "h",
        "15",
        "torque",
        "cap",
        "release",
        "fail",
        "signal",
        "story",
        "回生",
        "回生",
        "トルク",
        "トル",
        "ルク",
        "立上",
        "立上",
        "りと",
        "wheel",
        "decel",
        "一致",
        "一致",
        "しない",
        "場合",
        "場合",
        "制御失敗",
        "制御",
        "御失",
        "失敗",
        "ではなく",
        "plant",
        "brake",
        "drag",
        "疑",
        "next",
        "actions",
        "a",
        "rb",
        "07",
        "soc",
        "低条件",
        "低条",
        "条件",
        "再実行",
        "再実",
        "実行",
        "b",
        "battery",
        "internal",
        "resistance",
        "map",
        "固定",
        "固定",
        "して",
        "比較",
        "比較",
        "c",
        "hydraulic",
        "brake",
        "model",
        "drag",
        "term",
        "分離計測",
        "分離",
        "離計",
        "計測",
        "d",
        "report",
        "template",
        "trigger",
        "evidence",
        "rollback",
        "追加",
        "追加"
      ],
      "token_count": 125,
      "placeholder_keys": []
    }
  ]
};
